# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::569313928762:role/aws_param_eks

# pod 
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    component: cart
spec:
  containers:
    - name: frontend
      image: 569313928762.dkr.ecr.us-east-1.amazonaws.com/cart:2.0.0
  initContainers:
    - name: aws-ssm-param-store-initcont
      image: 569313928762.dkr.ecr.us-east-1.amazonaws.com/aws-ssm-param-store-initcont:1.0.0
  serviceAccountName: cart

# mapping for pod
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    component: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

