# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalogue
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::569313928762:role/aws_param_eks

# pod 
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    component: catalogue
spec:
  containers:
    - name: catalogue
      image: 569313928762.dkr.ecr.us-east-1.amazonaws.com/catalogue:2.0.1
      volumeMounts:
        - mountPath: /params
          name: params
  initContainers:
    - name: aws-ssm-param-store-initcont
      image: 569313928762.dkr.ecr.us-east-1.amazonaws.com/aws-ssm-param-store-initcont:1.0.1
      args: ["DOCUMENTDB:prod.catalogue.mongo"]
      volumeMounts:
        - mountPath: /params
          name: params
  serviceAccountName: catalogue
  volumes:
  - name: params
    emptyDir:
      sizeLimit: 100Mi

# mapping for pod
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    component: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

