apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  containers:
    - name: frontend
      image: 569313928762.dkr.ecr.us-east-1.amazonaws.com/frontend:2.0.1

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    component: frontend
    type: LoadBalancer       #we add this line because for frontend we need loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80